modLoader="javafml"
loaderVersion="${loader_range}"
issueTrackerURL="https://github.com/Natixe/GrimMod/issues"
license="CC BY-NC-SA 4.0"

[[mods]]
modId="grimmod"
namespace="grimmod"
version="${version}"
displayName="Grimmod"
authors="Natixe"
description='''
Mods ...
    '''
displayURL="https://github.com/Natixe/GrimMod"

[[dependencies.grimmod]]
modId="forge"
mandatory=true
versionRange="${forge_range}"
ordering="NONE"
side="BOTH"

[[dependencies.ironchest]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_range}"
ordering="NONE"
side="BOTH"